In [92]:
import pandas as pd
import numpy as np

In [93]:
pd.__version__

'2.2.3'

In [94]:
df=pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv')

In [95]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [96]:
df.index

RangeIndex(start=0, stop=2160, step=1)

In [97]:
df['Brand']=df['Brand'].str.lower()

In [98]:
df['Brand']=df['Brand'].str.replace(' ','_')

In [99]:
df['Brand'].unique().shape[0]

27

In [100]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [101]:
df['Price']=df['Final Price']

In [102]:
del df['Final Price']

In [103]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     msi   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      hp   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch    Price  
0    No  1009.00  
1    No   299.00  
2    No   789.00  
3    No  1199.00  
4    No   669.01

In [104]:
df.groupby('Brand').Price.max()

Brand
acer                3691.00
alurin               869.00
apple               3849.00
asus                5758.14
deep_gaming         1639.01
dell                3936.00
denver               329.95
dynabook_toshiba    1805.01
gigabyte            3799.00
hp                  5368.77
innjoo               431.38
jetwing              469.27
lenovo              5018.14
lg                  2399.00
medion              3799.00
microsoft           3747.91
millenium           2312.71
msi                 7150.47
pccom               1949.90
primux               599.41
prixton              329.95
razer               4999.01
realme               999.00
samsung             3699.01
thomson              436.56
toshiba              799.00
vant                1217.01
Name: Price, dtype: float64

In [105]:
df['Screen'].median()

np.float64(15.6)

In [106]:
df['Screen'].mode()

0    15.6
Name: Screen, dtype: float64

In [107]:
df['Screen'].fillna(15.6)

0       15.6
1       15.6
2       15.6
3       15.6
4       15.6
        ... 
2155    17.3
2156    17.3
2157    17.3
2158    13.4
2159    13.4
Name: Screen, Length: 2160, dtype: float64

In [108]:
df['Screen'].median()

np.float64(15.6)

In [109]:
Innjoo=df[df['Brand']=='innjoo']

In [110]:
Innjoo.shape

(6, 12)

In [111]:
X=Innjoo[['RAM','Storage','Screen']].values

In [112]:
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [117]:
XTX=X.T.dot(X)

In [118]:
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [119]:
Y=np.linalg.inv(XTX)

In [120]:
y=[1100, 1300, 800, 900, 1000, 1100]

In [123]:
r=Y.dot(X.T)

In [124]:
w=r.dot(y)

In [130]:
w

array([45.58076606,  0.42783519, 45.29127938])

In [131]:
result=0
for i in range(w.shape[0]):
    result= result + w[i]
print(result)

91.2998806299555


In [132]:
np.sum(w)

np.float64(91.2998806299555)