In [147]:
import numpy as np
import numpy.char as char

In [148]:
u=np.random.randint(low=0,high=15,size=(1,5))

In [149]:
v=np.random.randint(low=0,high=15,size=(5,1))

In [150]:
print(u)

[[10  1  7  8  7]]


In [151]:
print(v)

[[13]
 [11]
 [ 5]
 [ 6]
 [ 2]]


In [152]:
def multiplication(u,v):
    assert u.shape[1]==v.shape[0]
    
    result=0
    
    n=v.shape[0]

    for i in range(n):
        result=result + u[0,i]*v[i,0]
    return result

In [153]:
multiplication(u,v)

np.int64(238)

In [154]:
def matrix_multiplication(w,x):
    assert w.shape[1]==x.shape[0]
    n=np.zeros((w.shape[0],x.shape[1]))
    for i in range(w.shape[0]):
        for j in range(x.shape[1]):
            result=0
            for s in range(w.shape[1]):
                result=result + w[i,s]*x[s,j]
            n[i,j]=result
    return n

p=np.random.randint(low=0,high=15,size=(3,3))
print(p)
q=np.random.randint(low=0,high=15,size=(3,3))
print(q)

print(matrix_multiplication(p,q))

[[12  3 10]
 [ 5 11 11]
 [ 4  5  4]]
[[13 13  5]
 [13  1  9]
 [ 6 10  2]]
[[255. 259. 107.]
 [274. 186. 146.]
 [141.  97.  73.]]
